usethis::use_data(
    #ko2pathway,
    #cog_20,
    #cpd2kegg,
    dis_example,
    disbiome_data2,
    cog_example,
    ko_gson,
    #kom_gson,
    hmdb_gson,
    #hmdb_superclass,
    #hmdb_class,
    #hmdb_subclass,
    cog_category,
    cog_pathway,
    cpd_gson,
    smpdb_gson,
    #cog_pathway,
    #disbiome_data,
    #smpdb_data,
    human_gut2014,
    human_gut2016,
    human_skin,
    human_vagina,
    # taxid2genus,
    # taxid2sp,
    mb_examplelist,
    IPF,
    module_gson.KO,
    module_gson.ec,
    ec_gson,
    internal = TRUE,
    overwrite = TRUE,
    compress = "xz"
)
